### ISSUE TITLE
starting megxnet fails

### ISSUE THREAD

**Issue by paulfvliz** [MicroB3-IS/megxnet#1]
Hi 

I'm attempting to start up a megxnet service but I'm running into what might be some configuration issues. I followed the readme at the root of the project but cargo:run didn't out much and I was not able to access the service using http requests. 
In a second attempt I deployed the application war in tomcat7 container. In the catalina logs I found there error messages 

 --------------------------------------------------------------------------------
                Initializing ResTpl bundle: net.megx.esa
 --------------------------------------------------------------------------------
ERROR: Bundle net.megx.esa [44] Error starting file:/opt/megxnet/megx.net-web/../megx.net-workdir/target/megx-demo-workdir/plugins/net.megx.esa-1.1.0-SNAPSHOT.jar (org.osgi.framework.BundleException: Activator start error in bundle net.megx.esa [44].)
java.lang.IllegalArgumentException: named capturing group is missing trailing '}'
        at java.util.regex.Matcher.appendReplacement(Matcher.java:841)
        at java.util.regex.Matcher.replaceAll(Matcher.java:955)
        at java.lang.String.replaceAll(String.java:2223)
        at org.chon.common.configuration.impl.ConfigSonImpl.getConfig(ConfigSonImpl.java:72)
        at org.chon.common.configuration.impl.ConfigSonImpl.getConfig(ConfigSonImpl.java:49)
        at org.chon.cms.core.JCRAppConfgEnabledActivator.getConfig(JCRAppConfgEnabledActivator.java:73)
        at org.chon.cms.core.ResTplConfiguredActivator.onAppAdded(ResTplConfiguredActivator.java:38)
        at org.chon.cms.core.JCRApplicationActivator$1.addingService(JCRApplicationActivator.java:32)
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:896)
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:261)
        at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:184)
        at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:339)
        at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:273)
        at org.chon.cms.core.JCRApplicationActivator.start(JCRApplicationActivator.java:44)
        at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:629)
        at org.apache.felix.framework.Felix.activateBundle(Felix.java:1904)
        at org.apache.felix.framework.Felix.startBundle(Felix.java:1822)
        at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1192)
        at org.apache.felix.framework.StartLevelImpl.run(StartLevelImpl.java:266)
        at java.lang.Thread.run(Thread.java:748)

I got a tip that it might be json related. I went through all the json files in the project and made sure they were at least valid json. Do you have any idea what might be causing these errors and how I might be able to get this service running?

Thanks

**Comment by paulfvliz** [comment]
I was able to solve this by editing the 'commons.configson.resources' property in the system.properties file. There the ${megx.dev.source} value had to be replaced with the config directory in the workspace.
